export type PageId =
  | "dashboard"
  | "profile"
  | "settings"
  // Sales pages
  | "sales-orders"
  | "sales-customers"
  | "sales-quotations"
  | "sales-invoices"
  | "sales-returns"
  | "sales-reports"
  // Finance pages
  | "finance-ledger"
  | "finance-accounts"
  | "finance-journal"
  | "finance-payables"
  | "finance-receivables"
  | "finance-reports"
  | "finance-budget"
  // Inventory pages
  | "inventory-items"
  | "inventory-warehouses"
  | "inventory-transfers"
  | "inventory-adjustments"
  | "inventory-bom"
  | "inventory-production"
  | "inventory-reports"
  // Telegram service pages
  | "telegram-bots"
  | "telegram-2fa"
  | "telegram-notifications"
  | "telegram-broadcasts"
  | "telegram-automation"
  | "telegram-users"
  | "telegram-analytics"
  // Email/SMTP service pages
  | "smtp-overview"
  | "smtp-templates"
  | "smtp-send"
  | "smtp-logs"
  | "smtp-settings";
